_BASE_: "../Base-RCNN-FPN.yaml"
DE:
  CLASS_PROTOTYPES: "./all.pth"
  BG_PROTOTYPES: "drive/MyDrive/Copy of background_prototypes.vitl14.pth"
  BG_CLS_LOSS_WEIGHT: 0.2
  TOPK: 10
MODEL:
  META_ARCHITECTURE: "DevitNet"
  BACKBONE:
    NAME: "build_dino_v2_vit"
    TYPE: "base" # base, small
  WEIGHTS: ""
  MASK_ON: True
  RPN:
    HEAD_NAME: StandardRPNHead
    IN_FEATURES: ["res4"]
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001
  ROI_BOX_HEAD:
    NAME: ""
    NUM_FC: 0
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: True
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
DATASETS:
  TRAIN: ("train",)
  TEST: ("test",)
TEST:
  EVAL_PERIOD: 5000
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 5000
  CHECKPOINT_PERIOD: 5000
